Chapter9
AndreeaSburlea/FoodPin pull request #1
Opened 2022-04-14 14:54 UTC by AndreeaSburlea

## New features
-prototype cell

## Changes in code
-no changes
 
## Screenshot
<img width="462" alt="ch9-dark" src="https://user-images.githubusercontent.com/103115884/163416577-aeb6a2b7-4127-4ef5-8570-8941a85c8c92.png">
<img width="502" alt="ch9-light" src="https://user-images.githubusercontent.com/103115884/163416600-e4f254f3-33fe-4388-bceb-2a45651a7512.png">

2022-04-15 12:20 UTC, ralumarusca requested changes

2022-04-15 12:20 UTC, ralumarusca commented on FoodPin/FoodPin/RestaurantTableViewCell.swift
> +    @IBOutlet var thumbnailImageView: UIImageView!
IBOutlets should be private

2022-04-15 12:20 UTC, ralumarusca commented on FoodPin/FoodPin/RestaurantTableViewCell.swift
> +    }
Unused methods can be removed

2022-04-15 12:20 UTC, ralumarusca commented on FoodPin/FoodPin/RestaurantTableViewController.swift
> +        return cell
Align this line with the previous rows

2022-04-15 12:20 UTC, ralumarusca commented on FoodPin/FoodPin/RestaurantTableViewController.swift
> +    func configureDataSource() -> UITableViewDiffableDataSource<Section, String> {
Ideally there should be an empty line before and after each method to be more readable

2022-04-15 12:20 UTC, ralumarusca commented on FoodPin/FoodPin/RestaurantTableViewController.swift
> +    }
This enum can be moved at the top of the class, before the properties, so everything is grouped

2022-04-18 08:13 UTC, czegreanu commented
please rebase and fix-up the commits

2022-04-18 10:04 UTC, paulpop10 commented on FoodPin/FoodPin/RestaurantTableViewController.swift
> +    }
There should be an empty space after an closed brace

2022-04-18 10:37 UTC, paulpop10 approved these changes

2022-04-18 10:59 UTC, ralumarusca approved these changes

2022-04-18 11:55 UTC, merged