Chapter 30: Developing user notifications in iOS
AndreeaSburlea/FoodPin pull request #18
Opened 2022-05-24 11:48 UTC by AndreeaSburlea

## New features
- notifications

## Changes in code
- home screen notifications and actions

## Screenshot
<img width="375" alt="ch30 2" src="https://user-images.githubusercontent.com/103115884/170027605-f5128219-69eb-4d50-b4e4-1b473a02a5ad.png">
<img width="373" alt="ch30 1" src="https://user-images.githubusercontent.com/103115884/170027637-b85d1598-c1e2-4148-9aa4-26ac8dd25635.png">

2022-05-25 06:20 UTC, madalinaCojocaru1 requested changes

2022-05-25 06:20 UTC, madalinaCojocaru1 commented on FoodPin/FoodPin/Controller/RestaurantTableViewController.swift
> +
you can remove this empty line

2022-05-25 08:31 UTC, madalinaCojocaru1 approved these changes

2022-05-25 08:31 UTC, madalinaCojocaru1 commented on FoodPin/FoodPin/Controller/RestaurantTableViewController.swift
> +
you can remove this empty line

2022-05-26 11:19 UTC, paulpop10 approved these changes

2022-05-26 12:56 UTC, merged