Chapter 11: OOP structures and classes
AndreeaSburlea/FoodPin pull request #3
Opened 2022-04-20 07:31 UTC by AndreeaSburlea

## New features
- //MARK: comment marker

## Changes in code
- added a struct named Restaurant

## Screenshot
- no updates

2022-04-20 14:36 UTC, ralumarusca requested changes

2022-04-20 14:36 UTC, ralumarusca commented on FoodPin/FoodPin/Controller/RestaurantTableViewController.swift
> +                cell!.configureCell(name: self.restaurants[indexPath.row].name,
force unwrap is usually not a good idea, you can use optional or make a guard check

2022-04-20 14:36 UTC, ralumarusca commented on FoodPin/FoodPin/Controller/RestaurantTableViewController.swift
> +            // cell.favoriteImageView.isHidden = self.restaurants[indexPath.row].isFavorite
will you need these in the future? if not you can remove them

2022-04-21 09:26 UTC, paulpop10 commented on FoodPin/FoodPin/Model/Restaurant.swift
> +    var name: String = ""
These properties should be private and have public getters. You can talk to Vivi about how she did it

2022-04-26 06:23 UTC, ralumarusca approved these changes

2022-04-26 07:34 UTC, paulpop10 approved these changes

2022-04-26 08:26 UTC, merged